name: build

on:
  push:
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - variant: fts-polybase
            sqlserver: "2019"
            version: CU29-GDR1-ubuntu-20.04
          - variant: fts-polybase
            sqlserver: "2019"
            version: latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./${{ matrix.sqlserver }}/Dockerfile.${{ matrix.variant }}
          push: true
          tags: ghcr.io/ser-ssws/mssql-server:${{ matrix.sqlserver }}-${{ matrix.version }}-${{ matrix.variant }}
          build-args: |
            IMAGE_VERSION=${{ matrix.version }}
